### ISSUE TITLE
Update to Voyager rc06

### ISSUE THREAD

**Issue by Syer10** [programadorthi/kotlin-routing#1]
Due to some changes in the Navigator function signature, the current version of kotlin-routing does not work with the latest version of Voyager. A simple update to the dependencies would allow kotlin-routing to be used with the latest Voyager.

**Comment by programadorthi** [comment]
With kotlin-routing published to maven central I am thinking to migrate voyager modules to voygar repo and avoid breaking changes between their.

**Comment by programadorthi** [comment]
Closing issue because [PR](https://github.com/adrielcafe/voyager/pull/164) was opened
